# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KcjQzI_xBTyi0R0mDW4Xq5MeYzBcOmmc
"""

#Test

import pandas as pd